const express=require('express'),path=require('path'),{execFile}=require('child_process'),{promisify}=require('util');
const run=promisify(execFile),app=express(),PORT=process.env.PORT||3000;
app.use(express.json({limit:'16mb'}));app.use(express.static(path.join(__dirname,'public')));
async function btcCli(args){const cli=process.env.BITCOIN_CLI||'bitcoin-cli';const {stdout,stderr}=await run(cli,args,{timeout:30000,windowsHide:true,maxBuffer:16*1024*1024});if(stderr&&stderr.trim())throw Error(stderr.trim());return stdout.trim()}
app.get('/api/status',async(_q,r)=>{try{const [a,b]=await Promise.all([btcCli(['getblockchaininfo']),btcCli(['getmininginfo'])]);const i=JSON.parse(a),m=JSON.parse(b);r.json({ok:true,chain:i.chain,blocks:i.blocks,headers:i.headers,verificationprogress:i.verificationprogress,difficulty:i.difficulty,networkhashps:m.networkhashps,warnings:m.warnings||''})}catch(e){r.status(503).json({ok:false,error:e.message})}});
app.get('/api/wallet',async(_q,r)=>{try{const w=JSON.parse(await btcCli(['getwalletinfo']));r.json({ok:true,walletname:w.walletname,balance:w.balance,unconfirmed_balance:w.unconfirmed_balance,txcount:w.txcount})}catch(e){r.status(503).json({ok:false,error:e.message})}});
app.get('/api/template',async(_q,r)=>{try{const t=JSON.parse(await btcCli(['getblocktemplate','{"rules":["segwit"]}']));r.json({ok:true,height:t.height,previousblockhash:t.previousblockhash,bits:t.bits,target:t.target,curtime:t.curtime,mintime:t.mintime,transactions:t.transactions?.length||0,coinbasevalue:t.coinbasevalue,raw:t})}catch(e){r.status(503).json({ok:false,error:e.message})}});
function revhex(s){return s.match(/../g).reverse().join('')}
function compactVarint(n){if(n<0xfd)return Buffer.from([n]);if(n<=0xffff)return Buffer.from([0xfd,n&255,n>>>8]);if(n<=0xffffffff)return Buffer.from([0xfe,n&255,n>>>8,(n>>>16)&255,(n>>>24)&255]);let b=Buffer.alloc(9);b[0]=0xff;b.writeBigUInt64LE(BigInt(n),1);return b}
function pushdata(buf){if(buf.length<76)return Buffer.concat([Buffer.from([buf.length]),buf]);if(buf.length<256)return Buffer.concat([Buffer.from([0x4c,buf.length]),buf]);throw Error('coinbase data too long')}
function encodeScriptNum(n){let x=BigInt(n),a=[];while(x){a.push(Number(x&255n));x>>=8n}if(a.length===0)a=[0];if(a[a.length-1]&0x80)a.push(0);return Buffer.from(a)}
const ALPH='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
function b58(s){let n=0n;for(const c of s){const i=ALPH.indexOf(c);if(i<0)throw Error('invalid base58');n=n*58n+BigInt(i)}let h=n.toString(16);if(h.length%2)h='0'+h;let b=Buffer.from(h,'hex');let z=0;for(const c of s){if(c==='1')z++;else break}return Buffer.concat([Buffer.alloc(z),b])}
function checksumOk(b){const crypto=require('crypto');return crypto.createHash('sha256').update(crypto.createHash('sha256').update(b.subarray(0,-4)).digest()).digest().subarray(0,4).equals(b.subarray(-4))}
function addressScript(addr){if(addr.toLowerCase().startsWith('bc1')){const s=addr.toLowerCase(),pos=s.indexOf('1'),data=s.slice(pos+1);const map='qpzry9x8gf2tvdw0s3jn54khce6mua7l';let vals=[];for(const c of data.slice(0,-6)){const v=map.indexOf(c);if(v<0)throw Error('invalid bech32');vals.push(v)}let witver=vals.shift();if(witver>16)throw Error('invalid witness version');let acc=0,bits=0,out=[];for(const v of vals){acc=(acc<<5)|v;bits+=5;while(bits>=8){bits-=8;out.push((acc>>bits)&255)}}if(bits>=5||((acc<<(8-bits))&255))throw Error('invalid bech32 padding');const prog=Buffer.from(out);if((witver===0&&(prog.length!==20&&prog.length!==32))||(witver>0&&(prog.length<2||prog.length>40)))throw Error('invalid witness program');return Buffer.concat([Buffer.from([witver===0?0:0x50+witver,prog.length]),prog])}
const b=b58(addr);if(b.length<5||!checksumOk(b))throw Error('invalid base58 checksum');const ver=b[0],p=b.subarray(1,-4);if(ver===0x00&&p.length===20)return Buffer.concat([Buffer.from([0x00,0x14]),p]);if(ver===0x05&&p.length===20)return Buffer.concat([Buffer.from([0xa9,0x14]),p,Buffer.from([0x87])]);throw Error('unsupported address')}
function buildCoinbase(t,address){const crypto=require('crypto');const payout=addressScript(address);const height=pushdata(encodeScriptNum(t.height));const extra=crypto.randomBytes(8);const prefix=Buffer.from((t.coinbaseaux&&t.coinbaseaux.flags)||'','hex');let script=Buffer.concat([height,pushdata(prefix),pushdata(extra)]);if(script.length<2)script=Buffer.concat([script,Buffer.from([0])]);if(script.length>100)throw Error('coinbase scriptSig >100');const reserved=Buffer.alloc(32);const outs=[];const value=Buffer.alloc(8);value.writeBigUInt64LE(BigInt(t.coinbasevalue));outs.push(Buffer.concat([value,pushdata(payout)]));if(t.default_witness_commitment){const commitment=Buffer.from(t.default_witness_commitment,'hex');const cv=Buffer.alloc(8);outs.push(Buffer.concat([cv,pushdata(commitment)]))}const tx=Buffer.concat([Buffer.from([2,0,0,0,1]),Buffer.alloc(32,0),Buffer.alloc(4,255),compactVarint(script.length),script,compactVarint(outs.length),...outs,Buffer.from([1,32]),reserved,Buffer.alloc(4,0)]);return {tx,script}}
function dsha(b){const c=require('crypto');return c.createHash('sha256').update(c.createHash('sha256').update(b).digest()).digest()}
function txidLE(hex){return Buffer.from(dsha(Buffer.from(hex,'hex'))).reverse()}
function merkle(txs,coinbase){let a=[txidLE(coinbase.toString('hex')),...txs.map(x=>Buffer.from(x.txid,'hex').reverse())];while(a.length>1){let n=[];for(let i=0;i<a.length;i+=2)n.push(Buffer.from(dsha(Buffer.concat([a[i],a[i+1]||a[i]])).reverse()));a=n}return a[0]||Buffer.alloc(32)}
function buildJob(t,address){const cb=buildCoinbase(t,address).tx;const mr=merkle(t.transactions||[],cb);const header=Buffer.alloc(80);header.writeUInt32LE(t.version>>>0,0);Buffer.from(t.previousblockhash,'hex').reverse().copy(header,4);mr.copy(header,36);header.writeUInt32LE(t.curtime>>>0,68);Buffer.from(t.bits,'hex').reverse().copy(header,72);const body=Buffer.concat([compactVarint((t.transactions||[]).length+1),cb,...(t.transactions||[]).map(x=>Buffer.from(x.data,'hex'))]);return {height:t.height,header:[...header],target:[...Buffer.from(t.target,'hex')],bodyHex:body.toString('hex'),bits:t.bits,coinbasevalue:t.coinbasevalue}}
app.get('/api/job',async(req,res)=>{try{const address=String(req.query.address||'').trim();if(!address)throw Error('Payout address required');const t=JSON.parse(await btcCli(['getblocktemplate','{"rules":["segwit"]}']));if(t.capabilities&&!t.capabilities.includes('proposal')){}res.json({ok:true,...buildJob(t,address)})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.post('/api/submit',async(req,res)=>{try{const block=String(req.body?.block||'');if(!/^[0-9a-fA-F]+$/.test(block)||block.length<160||block.length%2)throw Error('Invalid block hex');const result=await btcCli(['submitblock',block]);res.json({ok:true,result:result||'accepted'})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.post('/api/send',async(req,res)=>{if(process.env.ENABLE_SEND!=='1')return res.status(403).json({ok:false,error:'Wallet send disabled. Set ENABLE_SEND=1 explicitly.'});const {address,amount,subtractFeeFromAmount=false}=req.body||{};const value=Number(amount);if(!address||!Number.isFinite(value)||value<=0)return res.status(400).json({ok:false,error:'Invalid address or amount'});try{const args=['sendtoaddress',address,String(value)];if(subtractFeeFromAmount)args.push('','', 'false','true');res.json({ok:true,txid:await btcCli(args)})}catch(e){res.status(503).json({ok:false,error:e.message})}});
app.listen(PORT,'127.0.0.1',()=>console.log(`OLD BTC MINER V5 -> http://127.0.0.1:${PORT}`));
